---
title: "ST211mini project"
author: "Group4"
output: html
---

## Set up
```{r}
library(dplyr)       
library(tidyr)      
library(readr)      
library(lubridate)
library(arm)
library(tidyselect)
library(ggplot2)
```

# Data Loading
```{r}
data<-read.csv("data/RWNS_cleaned.csv", header=TRUE,stringsAsFactors=TRUE)
```

# Data modeling

After looking through the variables, we decided to exclude the following categorical variables from our predictors: "fiveem", "sen", "computer", "gender"
```{r}
data<-read.csv("data/RWNS_cleaned.csv", header=TRUE,stringsAsFactors=TRUE)
```

# The First Regression
# Convert variables to factors
```{r}
data$sen <- as.factor(data$sen)
data$computer <- as.factor(data$computer)
data$gender <- as.factor(data$gender)
```

# Build the regression model
```{r}
model <- lm(ks4score ~ . - fiveem - sen - computer - gender - k3ma - k3sc - singlepar - tuition - exclude - absent, data = data)
```

# Summarize the model
```{r}
par(mfrow=c(2,2))
plot(model, which=c(1,2))
hist(rstandard(model), freq = FALSE ,
     main="Histogram of standardised residuals",
     cex.main=0.8, xlab="Standardised residuals")
```
