---
title: "ST211mini project"
author: "Group3"
output: html
self-contained: true
editor:
  render-on-save: true
preview: true
---
  
## Set up
```{r}
# set up
rm(list=ls())
library(dplyr)       
library(tidyr)      
library(readr)      
library(lubridate)
library(arm)
library(tidyselect)
library(ggplot2)
```

```{r}
# Data Loading
data<-read.csv("RWNS_final.csv", header=TRUE,stringsAsFactors=TRUE)
```

# Have a look at the data
```{r}
head(data)
summary(data)
```
## Explore the data with plots
```{r}

## gender: no clear relationship between gender and ks4score
ggplot(data, aes(x=gender,y=ks4score, color=gender)) + geom_boxplot()

## singlepar: students with or without single parent household have slightly different ks4score
ggplot(data, aes(x=singlepar,y=ks4score, color=singlepar)) + geom_boxplot()

## attitude: students with very_high attitude tend to have higher median ks4score
ggplot(data, aes(x=attitude,y=ks4score, color=attitude)) + geom_boxplot()

## FSM band: different percent of students in the school entitles to FSM have different ks4score
ggplot(data, aes(x=FSMband,y=ks4score, color=FSMband)) + geom_boxplot()

## hiquam: students with different level of mothers highest educational qualification have different ks4score
ggplot(data, aes(x=hiquamum,y=ks4score, color=hiquamum)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

## plot for IDACI_n and ks4score
ggplot(data, aes(x=IDACI_n, y=ks4score)) + geom_point()

## k3: no clear relationship between ks3 subject scores and ks4score ----
# select subset of data for k3 variable
data_k3 <- data[c("ks4score","k3en", "k3ma", "k3sc")]
# tidy up the data for ggplot
tidydata_k3 <- data_k3 %>%
  pivot_longer(cols = -"ks4score", names_to="k3", values_to="level")
tidydata_k3
ggplot(tidydata_k3, aes(x=k3,y=ks4score, color=k3)) + geom_boxplot()

# no clear relationship between gender and ks4score
ggplot(data, aes(x=gender,y=ks4score, color=gender)) + geom_boxplot() + labs(title = 'Boxplot between Gender and Ks4score')

# students with or without single parent household have slightly different ks4score
ggplot(data, aes(x=singlepar,y=ks4score, color=singlepar)) + geom_boxplot() + labs(title = 'Boxplot between Students with or without Single Parent and Ks4score')

# students with very_high attitude tend to have higher median ks4score
ggplot(data, aes(x=attitude,y=ks4score, color=attitude)) + geom_boxplot() + labs(title = 'Boxplot between Attitude and Ks4score')

# compare ks3 subject scores with ks4score
ggplot(data, aes(x=k3en,y=ks4score, color=k3en)) + geom_boxplot()+ labs(title = 'Boxplot between K3en and Ks4score')
ggplot(data, aes(x=k3ma,y=ks4score, color=k3en)) + geom_boxplot()+ labs(title = 'Boxplot between K3ma and Ks4score')
ggplot(data, aes(x=k3sc,y=ks4score, color=k3en)) + geom_boxplot()+ labs(title = 'Boxplot between K3sc and Ks4score')

```


